// Code generated by mkbuiltin.go. DO NOT EDIT.

package gc

import "cmd/compile/internal/types"

var runtimeDecls = [...]struct {
	name string
	tag  int
	typ  int
}{
	{"newobject", funcTag, 4},
	{"panicdivide", funcTag, 5},
	{"panicshift", funcTag, 5},
	{"panicmakeslicelen", funcTag, 5},
	{"panicmakeslicecap", funcTag, 5},
	{"throwinit", funcTag, 5},
	{"panicwrap", funcTag, 5},
	{"gopanic", funcTag, 7},
	{"gorecover", funcTag, 10},
	{"goschedguarded", funcTag, 5},
	{"goPanicIndex", funcTag, 12},
	{"goPanicIndexU", funcTag, 14},
	{"goPanicSliceAlen", funcTag, 12},
	{"goPanicSliceAlenU", funcTag, 14},
	{"goPanicSliceAcap", funcTag, 12},
	{"goPanicSliceAcapU", funcTag, 14},
	{"goPanicSliceB", funcTag, 12},
	{"goPanicSliceBU", funcTag, 14},
	{"goPanicSlice3Alen", funcTag, 12},
	{"goPanicSlice3AlenU", funcTag, 14},
	{"goPanicSlice3Acap", funcTag, 12},
	{"goPanicSlice3AcapU", funcTag, 14},
	{"goPanicSlice3B", funcTag, 12},
	{"goPanicSlice3BU", funcTag, 14},
	{"goPanicSlice3C", funcTag, 12},
	{"goPanicSlice3CU", funcTag, 14},
	{"printbool", funcTag, 16},
	{"printfloat", funcTag, 18},
	{"printint", funcTag, 20},
	{"printhex", funcTag, 22},
	{"printuint", funcTag, 22},
	{"printcomplex", funcTag, 24},
	{"printstring", funcTag, 26},
	{"printpointer", funcTag, 27},
	{"printiface", funcTag, 27},
	{"printeface", funcTag, 27},
	{"printslice", funcTag, 27},
	{"printnl", funcTag, 5},
	{"printsp", funcTag, 5},
	{"printlock", funcTag, 5},
	{"printunlock", funcTag, 5},
	{"concatstring2", funcTag, 30},
	{"concatstring3", funcTag, 31},
	{"concatstring4", funcTag, 32},
	{"concatstring5", funcTag, 33},
	{"concatstrings", funcTag, 35},
	{"cmpstring", funcTag, 36},
	{"intstring", funcTag, 39},
	{"slicebytetostring", funcTag, 40},
	{"slicebytetostringtmp", funcTag, 41},
	{"slicerunetostring", funcTag, 44},
	{"stringtoslicebyte", funcTag, 46},
	{"stringtoslicerune", funcTag, 49},
	{"slicecopy", funcTag, 51},
	{"slicestringcopy", funcTag, 52},
	{"reverse", funcTag, 53},
	{"decoderune", funcTag, 54},
	{"countrunes", funcTag, 55},
	{"convI2I", funcTag, 56},
	{"convT16", funcTag, 58},
	{"convT32", funcTag, 58},
	{"convT64", funcTag, 58},
	{"convTstring", funcTag, 58},
	{"convTslice", funcTag, 58},
	{"convT2E", funcTag, 59},
	{"convT2Enoptr", funcTag, 59},
	{"convT2I", funcTag, 59},
	{"convT2Inoptr", funcTag, 59},
	{"assertE2I", funcTag, 56},
	{"assertE2I2", funcTag, 60},
	{"assertI2I", funcTag, 56},
	{"assertI2I2", funcTag, 60},
	{"panicdottypeE", funcTag, 61},
	{"panicdottypeI", funcTag, 61},
	{"panicnildottype", funcTag, 62},
	{"ifaceeq", funcTag, 64},
	{"efaceeq", funcTag, 64},
	{"fastrand", funcTag, 66},
	{"makemap64", funcTag, 68},
	{"makemap", funcTag, 69},
	{"makemap_small", funcTag, 70},
	{"mapaccess1", funcTag, 71},
	{"mapaccess1_fast32", funcTag, 72},
	{"mapaccess1_fast64", funcTag, 72},
	{"mapaccess1_faststr", funcTag, 72},
	{"mapaccess1_fat", funcTag, 73},
	{"mapaccess2", funcTag, 74},
	{"mapaccess2_fast32", funcTag, 75},
	{"mapaccess2_fast64", funcTag, 75},
	{"mapaccess2_faststr", funcTag, 75},
	{"mapaccess2_fat", funcTag, 76},
	{"mapassign", funcTag, 71},
	{"mapassign_fast32", funcTag, 72},
	{"mapassign_fast32ptr", funcTag, 72},
	{"mapassign_fast64", funcTag, 72},
	{"mapassign_fast64ptr", funcTag, 72},
	{"mapassign_faststr", funcTag, 72},
	{"mapiterinit", funcTag, 77},
	{"mapdelete", funcTag, 77},
	{"mapdelete_fast32", funcTag, 78},
	{"mapdelete_fast64", funcTag, 78},
	{"mapdelete_faststr", funcTag, 78},
	{"mapiternext", funcTag, 79},
	{"mapclear", funcTag, 80},
	{"makechan64", funcTag, 82},
	{"makechan", funcTag, 83},
	{"chanrecv1", funcTag, 85},
	{"chanrecv2", funcTag, 86},
	{"chansend1", funcTag, 88},
	{"closechan", funcTag, 27},
	{"writeBarrier", varTag, 90},
	{"typedmemmove", funcTag, 91},
	{"typedmemclr", funcTag, 92},
	{"typedslicecopy", funcTag, 93},
	{"selectnbsend", funcTag, 94},
	{"selectnbrecv", funcTag, 95},
	{"selectnbrecv2", funcTag, 97},
	{"selectsetpc", funcTag, 62},
	{"selectgo", funcTag, 98},
	{"block", funcTag, 5},
	{"makeslice", funcTag, 99},
	{"makeslice64", funcTag, 100},
	{"growslice", funcTag, 102},
	{"memmove", funcTag, 103},
	{"memclrNoHeapPointers", funcTag, 104},
	{"memclrHasPointers", funcTag, 104},
	{"memequal", funcTag, 105},
	{"memequal0", funcTag, 106},
	{"memequal8", funcTag, 106},
	{"memequal16", funcTag, 106},
	{"memequal32", funcTag, 106},
	{"memequal64", funcTag, 106},
	{"memequal128", funcTag, 106},
	{"f32equal", funcTag, 107},
	{"f64equal", funcTag, 107},
	{"c64equal", funcTag, 107},
	{"c128equal", funcTag, 107},
	{"strequal", funcTag, 107},
	{"interequal", funcTag, 107},
	{"nilinterequal", funcTag, 107},
	{"memhash", funcTag, 108},
	{"memhash0", funcTag, 109},
	{"memhash8", funcTag, 109},
	{"memhash16", funcTag, 109},
	{"memhash32", funcTag, 109},
	{"memhash64", funcTag, 109},
	{"memhash128", funcTag, 109},
	{"f32hash", funcTag, 109},
	{"f64hash", funcTag, 109},
	{"c64hash", funcTag, 109},
	{"c128hash", funcTag, 109},
	{"strhash", funcTag, 109},
	{"interhash", funcTag, 109},
	{"nilinterhash", funcTag, 109},
	{"int64div", funcTag, 110},
	{"uint64div", funcTag, 111},
	{"int64mod", funcTag, 110},
	{"uint64mod", funcTag, 111},
	{"float64toint64", funcTag, 112},
	{"float64touint64", funcTag, 113},
	{"float64touint32", funcTag, 114},
	{"int64tofloat64", funcTag, 115},
	{"uint64tofloat64", funcTag, 116},
	{"uint32tofloat64", funcTag, 117},
	{"complex128div", funcTag, 118},
	{"racefuncenter", funcTag, 119},
	{"racefuncenterfp", funcTag, 5},
	{"racefuncexit", funcTag, 5},
	{"raceread", funcTag, 119},
	{"racewrite", funcTag, 119},
	{"racereadrange", funcTag, 120},
	{"racewriterange", funcTag, 120},
	{"msanread", funcTag, 120},
	{"msanwrite", funcTag, 120},
	{"checkptrAlignment", funcTag, 121},
	{"checkptrArithmetic", funcTag, 123},
	{"libfuzzerTraceCmp1", funcTag, 125},
	{"libfuzzerTraceCmp2", funcTag, 127},
	{"libfuzzerTraceCmp4", funcTag, 128},
	{"libfuzzerTraceCmp8", funcTag, 129},
	{"libfuzzerTraceConstCmp1", funcTag, 125},
	{"libfuzzerTraceConstCmp2", funcTag, 127},
	{"libfuzzerTraceConstCmp4", funcTag, 128},
	{"libfuzzerTraceConstCmp8", funcTag, 129},
	{"x86HasPOPCNT", varTag, 15},
	{"x86HasSSE41", varTag, 15},
	{"x86HasFMA", varTag, 15},
	{"armHasVFPv4", varTag, 15},
	{"arm64HasATOMICS", varTag, 15},
}

func runtimeTypes() []*types.Type {
	var typs [130]*types.Type
	typs[0] = types.Bytetype
	typs[1] = types.NewPtr(typs[0])
	typs[2] = types.Types[TANY]
	typs[3] = types.NewPtr(typs[2])
	typs[4] = functype(nil, []*Node{anonfield(typs[1])}, []*Node{anonfield(typs[3])})
	typs[5] = functype(nil, nil, nil)
	typs[6] = types.Types[TINTER]
	typs[7] = functype(nil, []*Node{anonfield(typs[6])}, nil)
	typs[8] = types.Types[TINT32]
	typs[9] = types.NewPtr(typs[8])
	typs[10] = functype(nil, []*Node{anonfield(typs[9])}, []*Node{anonfield(typs[6])})
	typs[11] = types.Types[TINT]
	typs[12] = functype(nil, []*Node{anonfield(typs[11]), anonfield(typs[11])}, nil)
	typs[13] = types.Types[TUINT]
	typs[14] = functype(nil, []*Node{anonfield(typs[13]), anonfield(typs[11])}, nil)
	typs[15] = types.Types[TBOOL]
	typs[16] = functype(nil, []*Node{anonfield(typs[15])}, nil)
	typs[17] = types.Types[TFLOAT64]
	typs[18] = functype(nil, []*Node{anonfield(typs[17])}, nil)
	typs[19] = types.Types[TINT64]
	typs[20] = functype(nil, []*Node{anonfield(typs[19])}, nil)
	typs[21] = types.Types[TUINT64]
	typs[22] = functype(nil, []*Node{anonfield(typs[21])}, nil)
	typs[23] = types.Types[TCOMPLEX128]
	typs[24] = functype(nil, []*Node{anonfield(typs[23])}, nil)
	typs[25] = types.Types[TSTRING]
	typs[26] = functype(nil, []*Node{anonfield(typs[25])}, nil)
	typs[27] = functype(nil, []*Node{anonfield(typs[2])}, nil)
	typs[28] = types.NewArray(typs[0], 32)
	typs[29] = types.NewPtr(typs[28])
	typs[30] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[25]), anonfield(typs[25])}, []*Node{anonfield(typs[25])})
	typs[31] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25])}, []*Node{anonfield(typs[25])})
	typs[32] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25])}, []*Node{anonfield(typs[25])})
	typs[33] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25]), anonfield(typs[25])}, []*Node{anonfield(typs[25])})
	typs[34] = types.NewSlice(typs[25])
	typs[35] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[34])}, []*Node{anonfield(typs[25])})
	typs[36] = functype(nil, []*Node{anonfield(typs[25]), anonfield(typs[25])}, []*Node{anonfield(typs[11])})
	typs[37] = types.NewArray(typs[0], 4)
	typs[38] = types.NewPtr(typs[37])
	typs[39] = functype(nil, []*Node{anonfield(typs[38]), anonfield(typs[19])}, []*Node{anonfield(typs[25])})
	typs[40] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[1]), anonfield(typs[11])}, []*Node{anonfield(typs[25])})
	typs[41] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[11])}, []*Node{anonfield(typs[25])})
	typs[42] = types.Runetype
	typs[43] = types.NewSlice(typs[42])
	typs[44] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[43])}, []*Node{anonfield(typs[25])})
	typs[45] = types.NewSlice(typs[0])
	typs[46] = functype(nil, []*Node{anonfield(typs[29]), anonfield(typs[25])}, []*Node{anonfield(typs[45])})
	typs[47] = types.NewArray(typs[42], 32)
	typs[48] = types.NewPtr(typs[47])
	typs[49] = functype(nil, []*Node{anonfield(typs[48]), anonfield(typs[25])}, []*Node{anonfield(typs[43])})
	typs[50] = types.Types[TUINTPTR]
	typs[51] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[11]), anonfield(typs[3]), anonfield(typs[11]), anonfield(typs[50])}, []*Node{anonfield(typs[11])})
	typs[52] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[11]), anonfield(typs[25])}, []*Node{anonfield(typs[11])})
	typs[53] = functype(nil, []*Node{anonfield(typs[2]), anonfield(typs[50])}, nil)
	typs[54] = functype(nil, []*Node{anonfield(typs[25]), anonfield(typs[11])}, []*Node{anonfield(typs[42]), anonfield(typs[11])})
	typs[55] = functype(nil, []*Node{anonfield(typs[25])}, []*Node{anonfield(typs[11])})
	typs[56] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2])})
	typs[57] = types.Types[TUNSAFEPTR]
	typs[58] = functype(nil, []*Node{anonfield(typs[2])}, []*Node{anonfield(typs[57])})
	typs[59] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, []*Node{anonfield(typs[2])})
	typs[60] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[2])}, []*Node{anonfield(typs[2]), anonfield(typs[15])})
	typs[61] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[1]), anonfield(typs[1])}, nil)
	typs[62] = functype(nil, []*Node{anonfield(typs[1])}, nil)
	typs[63] = types.NewPtr(typs[50])
	typs[64] = functype(nil, []*Node{anonfield(typs[63]), anonfield(typs[57]), anonfield(typs[57])}, []*Node{anonfield(typs[15])})
	typs[65] = types.Types[TUINT32]
	typs[66] = functype(nil, nil, []*Node{anonfield(typs[65])})
	typs[67] = types.NewMap(typs[2], typs[2])
	typs[68] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[19]), anonfield(typs[3])}, []*Node{anonfield(typs[67])})
	typs[69] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[11]), anonfield(typs[3])}, []*Node{anonfield(typs[67])})
	typs[70] = functype(nil, nil, []*Node{anonfield(typs[67])})
	typs[71] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[67]), anonfield(typs[3])}, []*Node{anonfield(typs[3])})
	typs[72] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[67]), anonfield(typs[2])}, []*Node{anonfield(typs[3])})
	typs[73] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[67]), anonfield(typs[3]), anonfield(typs[1])}, []*Node{anonfield(typs[3])})
	typs[74] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[67]), anonfield(typs[3])}, []*Node{anonfield(typs[3]), anonfield(typs[15])})
	typs[75] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[67]), anonfield(typs[2])}, []*Node{anonfield(typs[3]), anonfield(typs[15])})
	typs[76] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[67]), anonfield(typs[3]), anonfield(typs[1])}, []*Node{anonfield(typs[3]), anonfield(typs[15])})
	typs[77] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[67]), anonfield(typs[3])}, nil)
	typs[78] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[67]), anonfield(typs[2])}, nil)
	typs[79] = functype(nil, []*Node{anonfield(typs[3])}, nil)
	typs[80] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[67])}, nil)
	typs[81] = types.NewChan(typs[2], types.Cboth)
	typs[82] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[19])}, []*Node{anonfield(typs[81])})
	typs[83] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[11])}, []*Node{anonfield(typs[81])})
	typs[84] = types.NewChan(typs[2], types.Crecv)
	typs[85] = functype(nil, []*Node{anonfield(typs[84]), anonfield(typs[3])}, nil)
	typs[86] = functype(nil, []*Node{anonfield(typs[84]), anonfield(typs[3])}, []*Node{anonfield(typs[15])})
	typs[87] = types.NewChan(typs[2], types.Csend)
	typs[88] = functype(nil, []*Node{anonfield(typs[87]), anonfield(typs[3])}, nil)
	typs[89] = types.NewArray(typs[0], 3)
	typs[90] = tostruct([]*Node{namedfield("enabled", typs[15]), namedfield("pad", typs[89]), namedfield("needed", typs[15]), namedfield("cgo", typs[15]), namedfield("alignme", typs[21])})
	typs[91] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3]), anonfield(typs[3])}, nil)
	typs[92] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3])}, nil)
	typs[93] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[3]), anonfield(typs[11]), anonfield(typs[3]), anonfield(typs[11])}, []*Node{anonfield(typs[11])})
	typs[94] = functype(nil, []*Node{anonfield(typs[87]), anonfield(typs[3])}, []*Node{anonfield(typs[15])})
	typs[95] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[84])}, []*Node{anonfield(typs[15])})
	typs[96] = types.NewPtr(typs[15])
	typs[97] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[96]), anonfield(typs[84])}, []*Node{anonfield(typs[15])})
	typs[98] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[1]), anonfield(typs[11])}, []*Node{anonfield(typs[11]), anonfield(typs[15])})
	typs[99] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[11]), anonfield(typs[11])}, []*Node{anonfield(typs[57])})
	typs[100] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[19]), anonfield(typs[19])}, []*Node{anonfield(typs[57])})
	typs[101] = types.NewSlice(typs[2])
	typs[102] = functype(nil, []*Node{anonfield(typs[1]), anonfield(typs[101]), anonfield(typs[11])}, []*Node{anonfield(typs[101])})
	typs[103] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3]), anonfield(typs[50])}, nil)
	typs[104] = functype(nil, []*Node{anonfield(typs[57]), anonfield(typs[50])}, nil)
	typs[105] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3]), anonfield(typs[50])}, []*Node{anonfield(typs[15])})
	typs[106] = functype(nil, []*Node{anonfield(typs[3]), anonfield(typs[3])}, []*Node{anonfield(typs[15])})
	typs[107] = functype(nil, []*Node{anonfield(typs[57]), anonfield(typs[57])}, []*Node{anonfield(typs[15])})
	typs[108] = functype(nil, []*Node{anonfield(typs[57]), anonfield(typs[50]), anonfield(typs[50])}, []*Node{anonfield(typs[50])})
	typs[109] = functype(nil, []*Node{anonfield(typs[57]), anonfield(typs[50])}, []*Node{anonfield(typs[50])})
	typs[110] = functype(nil, []*Node{anonfield(typs[19]), anonfield(typs[19])}, []*Node{anonfield(typs[19])})
	typs[111] = functype(nil, []*Node{anonfield(typs[21]), anonfield(typs[21])}, []*Node{anonfield(typs[21])})
	typs[112] = functype(nil, []*Node{anonfield(typs[17])}, []*Node{anonfield(typs[19])})
	typs[113] = functype(nil, []*Node{anonfield(typs[17])}, []*Node{anonfield(typs[21])})
	typs[114] = functype(nil, []*Node{anonfield(typs[17])}, []*Node{anonfield(typs[65])})
	typs[115] = functype(nil, []*Node{anonfield(typs[19])}, []*Node{anonfield(typs[17])})
	typs[116] = functype(nil, []*Node{anonfield(typs[21])}, []*Node{anonfield(typs[17])})
	typs[117] = functype(nil, []*Node{anonfield(typs[65])}, []*Node{anonfield(typs[17])})
	typs[118] = functype(nil, []*Node{anonfield(typs[23]), anonfield(typs[23])}, []*Node{anonfield(typs[23])})
	typs[119] = functype(nil, []*Node{anonfield(typs[50])}, nil)
	typs[120] = functype(nil, []*Node{anonfield(typs[50]), anonfield(typs[50])}, nil)
	typs[121] = functype(nil, []*Node{anonfield(typs[57]), anonfield(typs[1]), anonfield(typs[50])}, nil)
	typs[122] = types.NewSlice(typs[57])
	typs[123] = functype(nil, []*Node{anonfield(typs[57]), anonfield(typs[122])}, nil)
	typs[124] = types.Types[TUINT8]
	typs[125] = functype(nil, []*Node{anonfield(typs[124]), anonfield(typs[124])}, nil)
	typs[126] = types.Types[TUINT16]
	typs[127] = functype(nil, []*Node{anonfield(typs[126]), anonfield(typs[126])}, nil)
	typs[128] = functype(nil, []*Node{anonfield(typs[65]), anonfield(typs[65])}, nil)
	typs[129] = functype(nil, []*Node{anonfield(typs[21]), anonfield(typs[21])}, nil)
	return typs[:]
}
